### ISSUE TITLE
"Licenses of transitive dependencies" shows unknown dependencies

### ISSUE THREAD

**Issue by maoo** [versioneye/versioneye-core#105]
I'm building this OSS project - https://github.com/symphonyoss/symphony-java-sample-bots/tree/develop - and uploading data [to Versioneye](https://www.versioneye.com/user/projects/57cada12939fc60037ebd03c) using the Maven Versioneye Plugin, with the following configuration (retrieved using mvn help:effective-pom`:)

```
      <plugin>
        <groupId>com.versioneye</groupId>
        <artifactId>versioneye-maven-plugin</artifactId>
        <version>3.9.2</version>
        <configuration>
          <trackPlugins>false</trackPlugins>
          <skipScopes>test,provided</skipScopes>
        </configuration>
      </plugin>
```

Running `mvn versioneye:list` I get the result posted on https://gist.github.com/maoo/75872d5c84be483847c6f3fd4e63929f

However, looking at the **_Licenses of transitive dependencies_** (at the bottom of the [Versioneye project page](https://www.versioneye.com/user/projects/57cada12939fc60037ebd03c), screenshot attached below), I see several dependencies that are not listed in the `versioneye:list` locally produced (nor using `mvn dependency:tree`); for example, `activation 1.1` is not part of the dependency list.

Where are these dependencies coming from? How can I investigate this issue further?

Please note that I've configured the Versioneye Maven plugin to exclude Maven Plugins and test/provided scoped dependencies.

<img width="809" alt="screen shot 2017-06-30 at 14 54 07" src="https://user-images.githubusercontent.com/327285/27736318-05023d8a-5da4-11e7-82cf-095300791a99.png">
)

**Comment by reiz** [comment]
Hi @maoo. Sorry for the late response. The button "transitive dependencies" at the project page resolves the dependency tree on the server, without using the maven-core. If you want to see your transitive dependencies on the server I recommend to use the VersionEye Maven Plugin for that. The plugin has a configuration option for transitive dependencies: 

```
<transitiveDependencies>false</transitiveDependencies>
```

So your complete configuration would look like: 

```
      <plugin>
        <groupId>com.versioneye</groupId>
        <artifactId>versioneye-maven-plugin</artifactId>
        <version>3.9.2</version>
        <configuration>
          <trackPlugins>false</trackPlugins>
          <transitiveDependencies>false</transitiveDependencies>
        </configuration>
      </plugin>
```

If you are using the `<transitiveDependencies>false</transitiveDependencies>` you don't need the `skipScopes` option because in transitive mode only `COMPILE` and `RUNTIME` scopes are analysed.
